### ISSUE TITLE
Light level on all blocks and I can't remove it

### ISSUE THREAD

**Issue by ItsDidz** [maruohon/minihud#100]
One day I opened up minecraft and randomly there was a light level number on all the blocks (although my brother might have accidently done it) and I cant remove it. I even uninstalled mini hud and mali lib, then reinstalled them and it was still there. Also I had turned on the light level for the info at the top left but i used that for days and it didnt happen until yesterday so Idk. I also reset all the settings. Please help its getting annoying.

**Comment by Spacebarium** [comment]
Attach a screenshot?

**Comment by maruohon** [comment]
Sounds like you have just enabled the Light Level Overlay. Use the hotkey from the `Renderer Hotkeys` category to turn it off again.

**Comment by maruohon** [comment]
I'm assuming this was solved.
