### ISSUE TITLE
Despawn sphere in nether not showing up

### ISSUE THREAD

**Issue by Miginijhof** [maruohon/minihud#103]
When i make and try to use a despawn sphere in the nether it doesnt show up

**Comment by maruohon** [comment]
Make sure both the main rendering (`H`) and the shape renderer (Renderer Hotkeys -> `shapeRenderer`) are still enabled in the nether, and that the shape is enabled, and that the color is not fully transparent (the first two letters after the  `#` are the alpha value, you want something around `60`).

**Comment by Copyablemite4** [comment]
I am having an issue similar. My despawn Sphere wont show up in overworld. I have shape render toggle on and I have "H" pressed so it shows the x,y,z cords in top left of my screen. How can I get it to show up?
