### ISSUE TITLE
Structure limits not shown in servers

### ISSUE THREAD

**Issue by cgomlobo** [maruohon/minihud#105]
I have the mod installed in the client, and when I use it in as server most services like info overlay or shapes work great, but when I want to see for example Nether fortress delimiters, they don't show up. It does not look like a config problem because when I have the same ones in a single player world it works perfectly.  Maybe there's something I have to do to make it work. By the way, installing it in the server does not make it work neither. Thanks in advance.

**Comment by maruohon** [comment]
The server would need to have the [Servux mod](https://www.curseforge.com/minecraft/mc-mods/servux) for the structure bounding boxes to work in MiniHUD. MiniHUD itself is client-side only and can't be used on the server side.

**Comment by cgomlobo** [comment]
Oh okay, didn't know that, thank you very much!
