### ISSUE TITLE
is it possible with forge optifine?

### ISSUE THREAD

**Issue by thinker010** [maruohon/minihud#107]
can ur minihud work in forgeoptifine?

**Comment by Skillnoob** [comment]
Depends on your Version you are playing in, if you are playing 1.14 + then only fabric works and i would also reccomend using sodium instead of optifine for fabric.

**Comment by maruohon** [comment]
There are Forge versions for 1.8 - 1.12.2 and also 1.14.4 and 1.15.2. 1.16 versions are coming at some point, but there is a lot of work left before I get the new code ready to be ported from 1.12.2 to the later versions, and I won't port the older code from Fabric to Forge anymore, it's just a waste of my development time.
