### ISSUE TITLE
Red overlay

### ISSUE THREAD

**Issue by luckykat07** [maruohon/minihud#109]
I loaded up mini-hud and all the blocks around me are red(as long as they are in 4 blocks off range). I checked through all off the settings but couldn't find anything to stop it. hopefully there is an easy fix, if so please tell me because I'm very new to this mod.

(edited by masa: moved the text from the title...)

**Comment by maruohon** [comment]
That sounds like the vanilla block solid faces debug renderer. No idea why that would be enabled on its own if you just installed the mod... You can assign a key for that in the Renderer Hotkeys category to toggle it off.

Or alternatively you can edit the config file at `.minecraft/config/minihud.json` and search for `RendererToggles` and then set all the options that start with `debug` to `false`.

**Comment by luckykat07** [comment]
it worked thanks so much!
