### ISSUE TITLE
[Suggestion] Info GPU vRam usage

### ISSUE THREAD

**Issue by Sar4h-3** [maruohon/minihud#111]
I have started to play more with shaders and noticed, that my not so good GPU is usually pretty high on vRam usage.
Would it be possible to make a info thing for that?

**Comment by maruohon** [comment]
I don't think that information is available via Java.
I believe for example Sodium's VRAM display is calculated by the mod internally, as it handles all the allocations etc. itself.

**Comment by Sar4h-3** [comment]
I didnt know if this was possible or not. i just noticed that that was missing and i wrote an issue. Thank you for the answer :)

**Comment by Micalobia** [comment]
Would it be possible to add a toggle that's only enabled if Sodium is installed?

**Comment by maruohon** [comment]
I don't really like adding direct support for specific mods, as it means that there will be more external dependencies for the dev environment and it gets annoying managing that and disabling some of those if doing snapshot updates and the other mod is not updated yet etc.

I'm assuming Sodium probably also doesn't want to do it for similar reasons, but in the upcoming refactored versions of malilib it would be trivial for Sodium to  add such an info line from its side to the same text HUD that MiniHUD uses.
