### ISSUE TITLE
Very bad :(

### ISSUE THREAD

**Issue by meee57** [maruohon/minihud#113]
Every time I try to destroy something (left click) it opens the config for the game. I can't change it and it makes the game unplayable. :(

**Comment by Spacebarium** [comment]
Did you change the hotkey to open the config menu to LMB? You can change it through Mod Menu without needing to be in-game

**Comment by meee57** [comment]
No, it is a glitch. It is set to H+c like the default. Restarting the instance and changing the hot key and changing it back don’t do anything either.

**Comment by maruohon** [comment]
"config for the game"? What menu opens exactly? If you didn't change the config menu hotkey `openConfigGui`, then did you maybe change the Shape Editor hotkey `shapeEditor`?

**Comment by meee57** [comment]
Yes the shape editor hotkey is right bracket and it works. Also when I removed the mod and reinstalled it and changed the setting back to what they were it fixed it
