### ISSUE TITLE
Can't access menu

### ISSUE THREAD

**Issue by literallythelamest** [maruohon/minihud#114]
I configured the menu overlay from "h+c" to "no key" and that was quite dumb of me but now I can't access it no matter what I (with my limited knowledge) do. Including deleting and reinstalling the mod. When I do so it seems to keep my configurations and maybe I am just not doing a proper job but I don't know what else to do.

**Comment by Krebs-Cycle** [comment]
You can go into the "config" folder in .minecraft and delete or edit the minihud.json file to fix it or you can download the mod menu mod and change it by opening the settings from the mod list.

**Comment by literallythelamest** [comment]
thank you I will try this out (:

**Comment by literallythelamest** [comment]
Instantly worked thank you
