### ISSUE TITLE
Server TPS display breaks with custom player lists

### ISSUE THREAD

**Issue by CodedSakura** [maruohon/minihud#119]
I'm hosting a 1.16.5 fabric vanilla compatible server and i have CarpetMod as well as StyledPlayerList.  
While the StyledPlayerList is managing the playerlist, the TPS shows as `<no valid data>`, but with `/log tps` is active, Carpet takes over the player list and the TPS display works fine.

Might be related to #43, based off of Patbox's findings on Patbox/StyledPlayerList#1

**Comment by maruohon** [comment]
This should be fixed in the latest build I did a little while ago, which is currently only on my server: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16.4

**Comment by CodedSakura** [comment]
It is indeed! Thanks!
