### ISSUE TITLE
[Suggestion] Container with NBT-Data viewer

### ISSUE THREAD

**Issue by MineAndDine96** [maruohon/minihud#126]
A thing like the shulker box preview, but for chests and other containers, which you copy with ctrl + Mousewheel. I know, it wouldnt be useful in survival at all and in creative not really too, but I thought I would just mention it.

**Comment by maruohon** [comment]
This is already how the Shulker Box Preview works - it works for any items that contain stored inventory contents in the same NBT tag structure/format. The preview just is not rendered for any items that don't currently contain any stored items.
