### ISSUE TITLE
Can't open my Minihud menu

### ISSUE THREAD

**Issue by Keeekomat** [maruohon/minihud#129]
I accidentally set my hotkey for opening the Menu to a weird combination, and I don't remember it. I tried to uninstall and install it again, so that the hotkey gets reseted but that didn't help. I can press the H key and it opens the little box with coordinates but i can't press H+C (the standard combination for the menu).

**Comment by Skillnoob** [comment]
go to your config folder and open minihud.json with a text editor like notpad.
then search with the search funktion crtl + f for openConfigGui and then you can modify the hotkey by modifying this line:
"keys": "H,C",

**Comment by Keeekomat** [comment]
Thank you that realy helped a lot

**Comment by maruohon** [comment]
If you have the Mod Menu mod, then you can also open the config menus via the config button there.

**Comment by Krunch1e** [comment]
> go to your config folder and open minihud.json with a text editor like notpad. then search with the search funktion crtl + f for openConfigGui and then you can modify the hotkey by modifying this line: "keys": "H,C",

everytime i try this i can only see some confusing symbols and all(My c key is broken so i need to change the config)

**Comment by maruohon** [comment]
@Krunch1e Well if you install the Mod Menu mod, then you don't have to deal with the config file manually, as you can open the config menu via the mod list.

This button in Mod Menu will open the MiniHUD config menu:
![image](https://user-images.githubusercontent.com/2331050/157414688-419f38ef-3a78-4c34-9e49-a12e40b2a7bb.png)

As for the config file (if you want to manually change the hotkey without installing Mod Menu), the config screen hotkey would be set here. It's just the key "names" separated by commas, without spaces:
![image](https://user-images.githubusercontent.com/2331050/157415153-8e28b7f7-36c9-49a4-9729-4bc66f84e4fd.png)
