### ISSUE TITLE
Enabling minihud shows weird borders by default.

### ISSUE THREAD

**Issue by qwertitty** [maruohon/minihud#132]
![Screenshot_266](https://user-images.githubusercontent.com/81822379/113433365-06dadf80-941a-11eb-9589-e201f5f561a2.png)

These purple and blue borders show up when I enable minihud. And I can't seem to find a way to disable the borders without completely disabling minihud. Any ideas?

**Comment by maruohon** [comment]
That is the player-following spawn chunks overlay. Set a hotkey for that in Renderer Hotkeys and turn it off.

Was it somehow enabled without you turning it on at some point? None of the overlays are supposed to be enabled by default.
