### ISSUE TITLE
Mini HUD Not Displaying Anything

### ISSUE THREAD

**Issue by Copyablemite4** [maruohon/minihud#133]
I have just recently switched from paper to fabric server and this is when my problem began. 

I tried seeing if the features where enabled and they are. I also have my H+R turned on to see shape rendering. I can open the home screen with H+C but any features I set to "True" does not appear. Also shape overlay does not work but did work on paper when I was running it. I have 1.16.4 mini HUD installed which is the latest that I can find on curse forge. 

Really not sure what the problem is. I haven't tried reinstalling it as I don't believe that the file is the problem because it worked fine on paper a couple of weeks ago. looking to get this fixed because I'm really missing "light level overlay" lol.  

Thanks

**Comment by DragonEggBedrockBreaking** [comment]
H is used to toggle on and off the entire mod. Make sure you didn’t press it by mistake.

**Comment by maruohon** [comment]
Do you have the main rendering option turned off? It's just `H` by default.

Unfortunately the config menus currently don't show the state of the options as they only have the hotkeys. This will be fixed/improved in the upcoming bigger updates.

**Comment by Copyablemite4** [comment]
@maruohon the main rendering "H" was the problem. 

Thanks so much,  I really need to write this stuff down haha.
