### ISSUE TITLE
Forge Edition for the latest versions

### ISSUE THREAD

**Issue by RaptaG** [maruohon/minihud#137]
Could you please make a Forge Edition for the latest versions of Minecraft?

**Comment by maruohon** [comment]
Forge ports are planned, but I'm only going to make them from the upcoming new major updates/versions.

There is still a bunch of work left before those next versions are even ready on the main development version, which is still on 1.12.2. And then I need to port that code to all the later MC versions on Fabric first, and then from that I'll make the Forge versions.

So I still can't give any kind of reliable ETA, all I can say is that the work/changes/additions on malilib is getting closer to being finished, and that has been slow going and keeping any progress from being made on the other mods for several months now. Once malilib is done, I can start on working on the stuff on the todo list for the other mods, and I need to somehow decide on what to include in this next release, as the entire todo list is really long and I have no idea how long it would take to do all of it...

**Comment by RaptaG** [comment]
Ok thanks for the feedback..
