### ISSUE TITLE
Minihud breaks pause menu

### ISSUE THREAD

**Issue by Noxally** [maruohon/minihud#138]
Adding older version of minihud to 20w14a causes pause menu to break as shown. Using minihud 0.19.0

Bounding boxes for the buttons remain in their ususal place, making navigating the menu somewhat of a minigame.

![image](https://user-images.githubusercontent.com/22868168/114285459-c271c400-9a57-11eb-9ac9-c2410bc44359.png)

**Comment by maruohon** [comment]
MiniHUD has not been updated to 21w10a or later and the vanilla rendering changes yet. I'm surprised an older version even runs at all without crashing. So using the 21w08b version on 21w10a or later is not recommended or supported, it's just simply broken due to the vanilla changes.
