### ISSUE TITLE
Render Overlays don't working on Servers

### ISSUE THREAD

**Issue by AstroPenguan** [maruohon/minihud#140]
I've got a own personal server in wich my friends and me play.
A little time ago we got the idea of making a slime farm so I installed minihud for making that and some future time farms but... well, neither the slime chunks overlay, nor the light over or any overlay of the mod but when I switch to a single player world, they appear.
Is there a reason or this is a bug?

**Comment by maruohon** [comment]
The slime chunk overlay needs you to tell the mod the seed when you are on a server. You can do that by running the vanilla `/seed` command, or if you know the seed but don't  have permission for the command, you can also do it with a regular chat message in the format `minihud-seed 12345`. The structure bounding boxes overlay needs a mod on the server to send the data, and that mod would usually be Servux.

But if even the light level overlay doesn't work, then do you have the mod main rendering disabled (by default with `H`)? Or are the individual renderers enabled still? Another thing that can break all the overlays are Optifine shaders.

**Comment by AstroPenguan** [comment]
Thanks for the response time (thought I would need to wait more xD)
Trying that right now, I'll tell if worked

**Comment by AstroPenguan** [comment]
I worked, Thanks for the support, I really fricked out but just needed to reconnect and press `H` sorry for the inconvenience.
