### ISSUE TITLE
The default hotkey for toggling the HUD (H) does not work

### ISSUE THREAD

**Issue by SanctusInfernum** [maruohon/minihud#142]
I logged on and the HUD worked, I tested toggling it on and off using H, but while it turned it off the first time, pressing H again did not turn it back on

**Comment by maruohon** [comment]
Did you press any other keys at the same time? Currently by default most hotkeys don't allow any extra keys to be held. Also for example Alt+tabbing in and out of the game can get the Alt key seemingly stuck on, as the game does not see the key release event.

**Comment by SanctusInfernum** [comment]
No, I didn't press any other keys, only H, and I didn't alt-tab either. I checked the config in .minecraft and the toggle key is still H. It just doesn't function for some reason, maybe I could try deleting and reinstalling

**Comment by maruohon** [comment]
Did this issue get resolved?
