### ISSUE TITLE
Water level indicator impossible to switch off

### ISSUE THREAD

**Issue by ReaperFBB** [maruohon/minihud#146]
I use miniHud for light levels and despawn spheres so don't always need it switched on. However, I also see a water height indicator which shows regardless of any settings or toggles. This means that water blocks are always rendered so you get ghost blocks showing if you look in a direction where there's water, even if the water wouldn't normally be visible.

This means that if I'm trying to play normally, the ghost blocks obscure anything that exists in between the player and the water which amkes things very awkward. I've searched through the settings and toggles and don't see anything that indicates what setting this would be. 

I've attached a couple of screenshots to demonstrate what I mean. Can anyone help?

![2021-05-24_13 56 45](https://user-images.githubusercontent.com/84720019/119351039-f1569900-bc97-11eb-9ffa-c7f8a4b55134.png)
![2021-05-24_13 56 21](https://user-images.githubusercontent.com/84720019/119351048-f4518980-bc97-11eb-9d56-67deb31a00bc.png)

**Comment by maruohon** [comment]
That is the vanilla debug renderer for water. You can bind a key for it in the Renderer Hotkeys category.

I have no idea why some of these seem to sometimes randomly turn on for some users... I assume you have never bound a hotkey for that renderer and turned it on either?

Most/all of these vanilla debug renderers currently also have various render state leaks and issues in the 1.15+ versions that I haven't fixed yet, so they aren't really even all that usable anyway at the moment...

**Comment by ReaperFBB** [comment]
No I'd never bound a key to this. I just assumed that I was missing something. But I've been playing a lot recently and it was driving me crazy.
I've bound a key to it now and managed to switch it off so thank you for the help and the swift response
