### ISSUE TITLE
21w14a Crashes when loading shapes

### ISSUE THREAD

**Issue by Allunaat** [maruohon/minihud#147]
I'm playing 21w14a snapshot and using 21w08b Minihud.

It works just fine but when I try to load shapes such as despawn sphere or any other the game just crashes.

I tried different snapshot versions of minihud and it crashes everytime.

**Comment by maruohon** [comment]
There is no version released yet that works correctly in 21w10a or later, due to the vanilla rendering changes in 21w10a.

I have it mostly working for 21w13a though, so there might be a build for that version at some point soon-ish.

**Comment by maruohon** [comment]
There have been updated builds for 21w13+ for a while now, so I'm closing this.
