### ISSUE TITLE
Multiplayer Bounding Boxes not working 1.17

### ISSUE THREAD

**Issue by csergi** [maruohon/minihud#152]
So I have spun up a fresh 1.17 fabric server, put servux in the mods folder, installed minihud client side, and did the following:
execute /seed to give minihud the seed to work with
toggled all all of the bounding boxes to true
enabled bounding boxes by binding a hot key
and visiting a shipwreck;
However I found no outline around the shipwreck.

**Comment by maruohon** [comment]
Which build of MiniHUD do you have? There are currently two builds for 1.17.0, and the second one (2021-06-09) specifically fixed the structure bounding box data syncing in multiplayer, since I hadn't updated Servux before that and noticed that the vanilla data format changed slightly.

**Comment by csergi** [comment]
Fixed it. Thank you
