### ISSUE TITLE
infobeecount staying at 0 

### ISSUE THREAD

**Issue by xibau** [maruohon/minihud#155]
the infobeecount stay at 0 whenever I point at a beehive or beenest

**Comment by maruohon** [comment]
It currently only works in single player. On a server there would need to be a mod that syncs the full block entity data for the hive (on request). That is planned for the Servux mod, but hasn't been implemented yet. The tooltip also mentions this (although not in detail about the multiplayer case).

**Comment by xibau** [comment]
Oh I didn't even think of it because I am on a local server, thanks for your answer !
