### ISSUE TITLE
MaLiLIB causing crash on my laptop

### ISSUE THREAD

**Issue by omega9380** [maruohon/minihud#159]
I'm trying to load Fabric onto my laptop.  My desktop has the exact same plugins and runs fine.  Every time I try to load MC with both MiniHUD and MaLiLIB, Minecraft crashes almost instantly.  If I remove MiniHUD, it still crashes but with different errors.  Removing both MiniHUD and MaLiLIB allows MC to load without issues.

MC version 1.17.1

Plugins:
Fabric-API 0.37.1
MaLiLIB-Fabric-1.16.4-0.10.0-dev.21+arne.8
MiniHUD-Fabric-1.16.4-0.19.0-dev.20210215.151117
OptiFabric-1.11.18
OptiFine HD U G9 pre32

Log file trying to load both MIniHUD and MaLiLIB: [https://pastebin.com/qCumbTtA](url)
Log file trying to load just MaLiLIB: [https://pastebin.com/9djwBwdu](url)

Like I mentioned, this very setup works fine on my desktop (Ryzen 7 2700X, 32GB RAM, Radeon RX5700XT, Windows 10 21H1) but causes these crashes on my laptop (Dell Latitude 7480, i5-7300U, 16GB RAM, Intel HD Graphics 620, Linux Mint 20.1).

I realize it is probably the hardware differences, but in my experience you can never have enough information when in the development phase! (And it may very well be me being dumb :) )

Thanks!

**Comment by altrisi** [comment]
Check the name of the files you are using again!

<details>

<summary>Solution</summary>

You are using 1.16 mods in a 1.17 installation! The 1.17 versions are on curseforge.

</details>
