### ISSUE TITLE
Shapes not showing on Paper-183 Server

### ISSUE THREAD

**Issue by TrekGIneer22** [maruohon/minihud#16]
As the title states I am playing on a MP server running Paper-183, we do not have access to the seed but other things I have read here say that is only used for slime chunks.  When I try to make a despawn sphere it doesn't seem to render into the world.  My Admins say it isn't anything they have disabled and that it may be an issue with the Spigot Server or a general bug.  I was hoping you could help us out.

Also is there no way to change the sphere radius?

**Comment by Solly-W** [comment]
Does it work in singleplayer?

**Comment by maruohon** [comment]
The shape system is in no way related to the server you are on. Did you assign a hotkey for the `shapeRenderer` in the Renderer Hotkeys category, to turn the shape renderer it self on? That is the most common confusion point of that system currently, and I need to add that toggle option to the Shapes menu to make it clearer that it needs to be turned on.

The Despawn Sphere is specifically meant for and calculated based on the mob despawn range, so it's not meant to be configurable. There will be a regular and configurable Sphere shape, along with several other common shapes in the Shape renderer system at some point, when I have the time to add them.

**Comment by TrekGIneer22** [comment]
oh...now I feel a little stupid getting my admins involved..though I would think if I had created and "enabled" a shape that THAT would "toggle" its render...could you maybe just do away with the separate render toggle all together since each shape has a toggle on it too?

thanks for the quick turn around

**Comment by maruohon** [comment]
Well I still prefer to have the separate toggle, that way you can easily disable the shape rendering without having flip on/off each individual shape, in case you have lots of them (in the future, when there will be more types...). But I will for sure add that toggle to the Shapes menu on the top, so it's easy to see that it exists and needs to also be enabled.

**Comment by TrekGIneer22** [comment]
cool... I will check that toggle when I get home and close this if that's the embarrassing issue

**Comment by maruohon** [comment]
Not really embarrassing... my mods definitely have lots of usability issues currently, with some of these options scattered around that users don't know about before they run into issues and are told about them once...

**Comment by TrekGIneer22** [comment]
Ok so that was the issue...but I also don't see how to make any other shape, there is a searchable drop down next to the add shape button but it is populated by info titles (biome, biome registry, facing, etc.)

**Comment by Solly-W** [comment]
The shape renderer is incomplete. Currently only the despawn sphere exists.

**Comment by TrekGIneer22** [comment]
ahh I see maruohon said there WILL be...I read there ARE

anyway Im all figured out so thatnks and bye
