### ISSUE TITLE
[Bug] Multiplayer Bounding Boxes not working 1.17.1

### ISSUE THREAD

**Issue by LosBagros** [maruohon/minihud#160]
Same problem as #152 but in 1.17.1

**Comment by maruohon** [comment]
I need more information than that. Does the server have the Servux mod? Which bounding boxes did you try? I think the Nether Fortress box might be broken in the current 1.17.x versions.

**Comment by LosBagros** [comment]
Server does not have servux mod.
I tried nether fortress and village.
Server version 1.17.1

**Comment by maruohon** [comment]
If the server doesn't have the Servux mod, then MiniHUD can't get the structure bounding box data from anywhere in multiplayer.

**Comment by LosBagros** [comment]
But servux does not run 1.17.1

**Comment by LosBagros** [comment]
Pls make servux running on 1.17.1

**Comment by maruohon** [comment]
The 1.17.0 version of Servux does also work in 1.17.1. I had forgotten to update the file details on CurseForge to reflect that though, so I did it now.
