### ISSUE TITLE
[Bug] Hotkey doesn't work when pressing other keys at the same time

### ISSUE THREAD

**Issue by wu4x** [maruohon/minihud#162]
When i press my hotkey (F4) it doesn't toggle the menu if i am holding any other key, why?

**Comment by maruohon** [comment]
This is not a bug, it's intended behavior (at least as far as the implementation and current default settings go). The default settings for the keybinds don't allow any extra keys to be pressed. You can change that for any keybinds via the Advanced Keybind Settings widget/menu that is to the right of the keybind config button.

In future versions the default setting will be to allow extra keys (but that change will not automatically take effect if you have existing configs, unless I add a "config fixer" when loading old configs in that newer version).

**Comment by wu4x** [comment]
Allright thank you very much! Also thank you for the great mod :D
