### ISSUE TITLE
1.17.1 Bounding Box Server

### ISSUE THREAD

**Issue by DarkxStorm** [maruohon/minihud#174]
The bounding box renders in the single player world but when I try it on a server it doesn't render. Other things like slime chunk, light overlay do render but bounding box doesn't and I do have op on the server. Tried to render in all 4 gamemodes but unsuccessful

**Comment by Krebs-Cycle** [comment]
You also need to have servux on the server for bounding boxes in minihud to work. https://www.curseforge.com/minecraft/mc-mods/servux

**Comment by krispyking24** [comment]
why dose the server need that plugin for structure bounding boxes to show

**Comment by maruohon** [comment]
@krispyking24 Because the vanilla game does not needs the bounding box data on the client, so the vanilla server does not send the data to the clients. So the client doesn't know where any bounding boxes might be.
