### ISSUE TITLE
Minecraft 1.18 Support

### ISSUE THREAD

**Issue by MatthewManley** [maruohon/minihud#181]
I did some work to update the mod to minecraft version 1.18. Everything seems to work fine, I wasn't exactly sure I did all the required changes correctly but everything that I use seems to work correctly. I can open a pull request but it doesn't appear that there is a 1.18 branch so I figured opening an issue and linking to my branch would be the best option.

https://github.com/MatthewManley/minihud/tree/fabric_1.18

For anyone seeing this and would like to test out my release, [it can be found here, use at your own risk](https://github.com/MatthewManley/minihud/releases/tag/1.18)

**Comment by vacla** [comment]
There is here one temperary by masa already https://masa.dy.fi/tmp/minecraft/mods/misc_test_versions/minihud-fabric-1.18.0-0.19.0-dev.20211204.230657.jar

**Comment by MatthewManley** [comment]
Awesome, didn't know that existed
