### ISSUE TITLE
overlayLightLevel crashes game

### ISSUE THREAD

**Issue by Noraksing** [maruohon/minihud#187]
Turning on the overlayLightLevel renderer crashes the game. To recreate, simply keybind a key to overlayLightLevel and toggle it on in the game.

below are some crash reports:

[crash-2021-12-16_23.53.36-client.txt](https://github.com/maruohon/minihud/files/7729252/crash-2021-12-16_23.53.36-client.txt)

https://crashy.net/GYShN4Yj2yvpvO5uyb9L

https://bytebin.lucko.me/iSzL07mbI

**Comment by maruohon** [comment]
You seem to be using the 1.17.1 malilib and MiniHUD versions on 1.18.

**Comment by Noraksing** [comment]
updating malilib to malilib-fabric-1.18.0-0.10.0-dev.26.jar still crashes the game.

Here are the crash logs:

[crash-2021-12-17_20.38.45-client.txt](https://github.com/maruohon/minihud/files/7735507/crash-2021-12-17_20.38.45-client.txt)

https://bytebin.lucko.me/6pUEq97meM

https://crashy.net/RIM4WULP5ITHZL3cHpxW

**Comment by vacla** [comment]
@sleepybraincells you need to update minihud also

**Comment by Noraksing** [comment]
fixed once minihud and malilib are updated to 1.18
