### ISSUE TITLE
Unable to toggle Nether Fortress bounding box.

### ISSUE THREAD

**Issue by Sh0oo** [maruohon/minihud#191]
I'm new to MiniHud so I'm unsure if I'm doing something wrong but I have enabled overlayStructureMainToggle aswell as Nether Fortress in structures, but the keybind does not seem to toggle the bounding box. I've tried different keybinds but nothing seems to work, I'm currently playing on 1.18.1 if that helps.

**Comment by Sh0oo** [comment]
Forgot to mention that I am playing on a server, I do not own the server though.

**Comment by maruohon** [comment]
On a server the server would need to have a mod to send the structure data for MiniHUD when it asks for it. If the servers runs Fabric, then you can simply add the [Servux](https://www.curseforge.com/minecraft/mc-mods/servux/files) mod to the server (or ask the owner), and then it will just work.

But if it's not a Fabric server then it's not as straightforward. If it's a vanilla or Realms server, then it just won't work. If it's a Spigot/Paper server, then it may be possible to get it working by using the BBOR (Bounding Box Outlines Reloaded) mod's Bukkit plugin on the server, and then you would need the MasaGadget mod on the client, which is an add-on mod made by someone else for my client mods. It adds support to MiniHUD for reading the BBOR plugin's data format. You can get the early 1.18 build of that mod from here: https://github.com/plusls/MasaGadget/actions

**Comment by Sh0oo** [comment]
Alright yeah it won't work then as it is a vanilla server, thank you though.

**Comment by sakurawald** [comment]
> On a server the server would need to have a mod to send the structure data for MiniHUD when it asks for it. If the servers runs Fabric, then you can simply add the [Servux](https://www.curseforge.com/minecraft/mc-mods/servux/files) mod to the server (or ask the owner), and then it will just work.
> 
> But if it's not a Fabric server then it's not as straightforward. If it's a vanilla or Realms server, then it just won't work. If it's a Spigot/Paper server, then it may be possible to get it working by using the BBOR (Bounding Box Outlines Reloaded) mod's Bukkit plugin on the server, and then you would need the MasaGadget mod on the client, which is an add-on mod made by someone else for my client mods. It adds support to MiniHUD for reading the BBOR plugin's data format. You can get the early 1.18 build of that mod from here: [plusls/MasaGadget/actions](https://github.com/plusls/MasaGadget/actions)

Fot 1.20.1, it's ok to install bbor bukkit plugin in paper/purpur server, and install bbor fabric mod in clietn.
But if your client only install MiniHud and MasaGadget, you can't see the structure outline. (Maybe MasaGadget doesn't add BBOR protocol for minihud)

PS: MiniHUD says it supports bbor mod, so I just guess there are some difference between `bbor mod` and `bbor bukkit plugin`
