### ISSUE TITLE
[BUG] Light level overlay is red at 7

### ISSUE THREAD

**Issue by 1upbyte** [maruohon/minihud#192]
Since 1.18, mobs can only spawn at light level 0. Having the light overlay still be red when the light level is 7 is a bug.

Optionally, a config option to change when the light overlay should be red could be added and set to default to 0.

![image](https://user-images.githubusercontent.com/55856800/147690442-d388f01e-f1e4-4cf4-84a0-6d2c898a4139.png)

**Comment by maruohon** [comment]
There is already a config for that, in Generic -> `lightLevelThreshold`. And I have changed the default value of it in my code to reflect the 1.18 change. That early build of the mod for 1.18 just doesn't have that change yet.

**Comment by 1upbyte** [comment]
ok thanks!
