### ISSUE TITLE
No light level Overlay in Minecraft 1.12.2

### ISSUE THREAD

**Issue by RainerZufall187** [maruohon/minihud#196]
I have no option to display the overlay for the light level. In my render hotkey setting only the following can be seen.
I use the Mini HUD version 0.13.1 for Forge Minecraft version 1.12.2.

![image](https://user-images.githubusercontent.com/40537673/148407616-b02facc1-c7ad-42b9-a06f-fe2a4bdc9bf9.png)

Please add the Light Level Overlay to this version.

**Comment by maruohon** [comment]
That 0.13.1 version is simply very old and outdated. There are newer versions of the mod(s) available for 1.12.2 here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.12.2 They will also get uploaded to CurseForge again at some point, when they reach a nice new "release state" such that no new things are immediately planned anymore.

I don't actually remember if that 1.12.2 Forge version has the light level overlay, but at least the LiteLoader version does. In many cases you can run both Forge and LiteLoader together, unless you have a mod which conflicts somehow with LiteLoader. I'm assuming you are using other Forge mods to require using Forge in the first place... if you don't, then I'd recommend LiteLoader instead, as those mod versions are always more recent and have more features.
