### ISSUE TITLE
FPS inconsistency 

### ISSUE THREAD

**Issue by EZEILL** [maruohon/minihud#2]
For some reason MiniHud is capping the fps I have at 20 fps while Minecraft's built in fps and Journey Map both show that my fps is MUCH higher.

**Comment by maruohon** [comment]
Oh right... I think I broke it in the latest update when I changed the text updating to only happen once per game tick instead of each rendered frame... oops. Thus the "20 fps" because of 20 TPS.

**Comment by EZEILL** [comment]
Anything I can do to fix it on my end, or do I need to wait for another update?

**Comment by maruohon** [comment]
Nope, the only thing you can do for now is use the previous version if you rely on the FPS counter. I will probably fix it and make a new release a bit later today though. I'm just currently working on some uni assignment work stuff first.

**Comment by EZEILL** [comment]
Alright, seems I'm having all sorts of trouble with the mod pack I'm putting together lol, I fix one thing then another pops up. Thats what I get for having 160+ mods.
