### ISSUE TITLE
Fabric is crashing when loading minihud

### ISSUE THREAD

**Issue by ziraw** [maruohon/minihud#20]
if i try to load up minihud the game wouldnt even start.
It would just crash whenloading up...

can someone help me please?

yes I installed the Fabrich-API, I use the 0.5.1.36 installer for minecraft 1.14.4
and minihud-fabric-1.14.4-0.19.0-dev.20190720.191339.
and thats the API; fabric-api-0.4.0+build.240-1.14

Thanks for Helping me

**Comment by Nike020410** [comment]
Did you forget Malilib?

**Comment by ziraw** [comment]
@Nike020410  i do not know what this is... 
could very well be

**Comment by maruohon** [comment]
malilib is a library mod required by all my other client-side mods.

It can be found here:
https://www.curseforge.com/minecraft/mc-mods/malilib/files

**Comment by vacla** [comment]
if you only use masa's mods, you don't need fabric api also

**Comment by ziraw** [comment]
@maruohon so i will put it in the mods folder? right?

**Comment by vacla** [comment]
yeah

**Comment by ziraw** [comment]
omg thank you :D

**Comment by vacla** [comment]
can you close the issue also?

**Comment by ziraw** [comment]
yeas one question, how do i display structure bounding stuff and all this stuff?

**Comment by vacla** [comment]
in singleplayer and quickcarpet server it will work, in the configs you can toggle mainstructurerenderer or something like that and then also the structure you want to see

**Comment by maruohon** [comment]
For structure bounding boxes, you enable the types you want to see on the `Structures` tab in the config menu (`H + C`), and then you also need to set a hotkey for `overlayStructureMainToggle` on the `Renderer Hotkeys` tab, to be able to turn on the structure renderer itself.

Note that the structure bounding boxes currently only work in single player, or on QuickCarpet servers. I'm also slowly working on my own server-side mod for sending the data.

**Comment by ziraw** [comment]
thanks for all the help :)

**Comment by ziraw** [comment]
it doesnt work ahhhh 
it says showing box: ON bla bla but i dont get it to work what am i doing wrong

**Comment by vacla** [comment]
are you on singleplayer or quickcarpet server, cause otherwise it won't work

**Comment by ziraw** [comment]
yes i am

**Comment by vacla** [comment]
overlaystructuremaintoggle on?

**Comment by ziraw** [comment]
yes

**Comment by vacla** [comment]
can you show a send a screenshot of your f3 screen and also from the structure?

**Comment by ziraw** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/56176226/66258987-0bcebc80-e7ac-11e9-9c3c-faa70a96cb43.png)

**Comment by maruohon** [comment]
Do you have the MiniHUD main rendering (hotkey `H`) still on? If that is on, and the structure renderer was toggled on, and you enabled the Nether Fortress structure type, then it *should* work in single player.

**Comment by ziraw** [comment]
yes i had to press h..
tahnks dude <3

**Comment by ziraw** [comment]
can i somehow tell the mod my seed?

**Comment by vacla** [comment]
you only need it for slime chunks, but you can do `/seed` if you have OP or `minihud-seed <seed>` if you know the seed and replace `<seed>` with the actual seed.

**Comment by ziraw** [comment]
slime chunks aparently do work on servers..
thank you guys. I think we can transform this thread into a MiniHUD tutorial at this point... 
xD
