### ISSUE TITLE
[Request] Show Time / Day Of Overworld In The Nether And The End

### ISSUE THREAD

**Issue by SleepyCatten** [maruohon/minihud#202]
Current functionality:
Shows the local day / time of each world (world, nether, the_end).

Requested functionality:
Allow players to select whether to localise the day/time to each world or to show only the day/time of the overworld.

**Comment by maruohon** [comment]
The mod currently shows the time of the current world/dimension. In multiplayer that is also the only thing it can do (without a server-side mod sending some other dimension's time to the mod). But in vanilla the time is also always the same in all dimensions. Basically the overworld has the "only actual" running time, and all the other dimensions just read the overworld's time. So in vanilla context there is nothing that can be changed about this.

**Comment by SleepyCatten** [comment]
Thank you for the quick reply on this one. I don't know whether it's relevant, but there is a datapack that I believe allows this functionality:
https://www.planetminecraft.com/data-pack/timetracker-12-14-hour-time-in-minecraft-datapack/

I believe this plugin does it too:
https://www.spigotmc.org/resources/coordinates-display-coords-and-other-info-in-action-bar-or-boss-bar-lightweight.80304/

**Comment by maruohon** [comment]
But isn't that datapack showing basically the exact same thing MiniHUD's "mc time" info line shows? I'm not seeing what more MiniHUD could show here? And like I mentioned, in the vanilla context (without some server-side mod that decouples the dimensions from each other), there is just one clock/time that is common to all the dimensions.

**Comment by SleepyCatten** [comment]
Thanks for the reply and my apologies if I'm being dense. (It's probably me misunderstanding you here.)

The datapack shows the overworld dimension time, not the different times in the nether and the end. Currently, the day/time for my dimensions are entirely different to each other, so the time showing in MiniHUD is showing the specific day/time of the world dimension it's in.

For example, when in the main world dimension, the day was something like 300 and evening, it was day 200 something and midday in the nether. MiniHUD displayed the day/time relative to the individual dimension.

By comparison, the datapack and plugin I've linked to show the time only from the overworld dimension even when you're in another dimension.

**Comment by maruohon** [comment]
Then I assume you are on some kind of modded server, maybe for example Spigot/Paper servers unlink the dimension times from eachother? But even if that's the case, MiniHUD can't know about the overworld time while you are in another dimension, unless there would be a server side mod or plugin that would send the time of another dimension on request. The client only has one world, and that's always the world the player is currently in. So in a vanilla setting that's the only dimension that is accessible to the mod directly on the client while you are on a server.

It's possible that syncing the time of other dimensions might end up as part of my Servux mod at some point, but that doesn't help you if you play on some Spigot/Paper server. Servux currently only exists for Fabric, and other than that I myself will at most port it to Forge at some point.

**Comment by SleepyCatten** [comment]
I am indeed on a Paper server. I've been on a Spigot/Paper server before with either that datapack or that plugin and they've still both displayed the overworld dimension time. In fact, I believe both added in this functionality when I requested.

This said, I do not want to keep troubling you with this. Thank you very much for your thoughts on it 💟

**Comment by maruohon** [comment]
Well yes a data pack or plugin can do it because those run on the server side, and they just send the info to the client either as action bar messages, or via the bossbar or other "vanilla hacks". But MiniHUD alone doesn't have any way to get any data fro the server about a dimension other than the dimension your player is currently in. (And even so vanilla usually only syncs data to the client that the vanilla client actually needs for something, which usually means for something related to rendering the world. And time of day is one of those things, since it's needed for the sky (sun/moon/stars) rendering and the day/night cycle (light vs. darkness) etc.)

**Comment by SleepyCatten** [comment]
*nods* Sorry for being a dumb with this one. I'll either look into something on the server side to synchronise the day/time on the worlds or switch to a different method to show the time.

Many thanks x
