### ISSUE TITLE
Unable to click..?

### ISSUE THREAD

**Issue by GalaxysWithFiles** [maruohon/minihud#206]
For some reason, whenever i have the fully released version of the mod in my mods folder, 9/10 of my clicks dont register at all unless im holding a key on my keyboard..? i dont know if its a hotkey problem thats bound to my left click that doesnt allow it to work or what, so for now i cant use the mod because it makes it way more annoying to do anything. (edit: and yes i did test to make sure it was specifically this mod, i tested it 2 times with and without, all times either allowed me/disallowed me to click)

**Comment by maruohon** [comment]
It does sound like you have potentially something bound to just left (or right?) click (which one is it or is it both?). Go over your hotkey configs and see if you can find such a bind.

**Comment by GalaxysWithFiles** [comment]
yep im dumb... it was a keybind to one of the info lines, thanks!
