### ISSUE TITLE
honeyTooltips

### ISSUE THREAD

**Issue by Flus1234** [maruohon/minihud#207]
Minecraft 1.18.1, singe player
minihud-fabric-1.18.1-0.21.2

Honey level tooltip (Generic - honeyTooltips) feature on the beehive or bee nest when i hover them in the inventory dosn't work.
Though option Info Lines - infoHoneyLevel work well.
![2022-01-22_22 26 25](https://user-images.githubusercontent.com/61036027/150650192-ad44eca2-f85b-477c-93bf-3ef5c1957995.png)

**Comment by maruohon** [comment]
It looks like the `BlockStateTag` NBT tag does not get added to creative Ctrl + pick blocked hives. It only gets added if you break the hive.

**Comment by Flus1234** [comment]
Indeed, information about honey is displayed correctly when i break the hive.
