### ISSUE TITLE
mainRenderingToggle keybind does not save to config.

### ISSUE THREAD

**Issue by PINPAL** [maruohon/minihud#210]
When setting a different keybind or removing the keybind for `mainRenderingToggle` it does not save to the config file. 
This means it's save state is lost upon closing and reopening the game.

# Expected Behaviour
Keybind will be written to config and persist between game reloads.

# Steps to Reproduce
1. Launch Minecraft with `minihud-fabric-1.18.1-0.21.3`
2. Navigate to the config for MiniHUD.
3. Change keybind for `mainRenderingToggle`
4. Observe keybind working as intended.
5. Close and relaunch the game.
6. Observe keybind has been reset to default.

**Comment by maruohon** [comment]
Which malilib version do you have? This should be fixed in 0.11.5 or later.

**Comment by PINPAL** [comment]
> Which malilib version do you have? This should be fixed in 0.11.5 or later.

Updated to the latest version of Malilib. Issue is now fixed, thanks.
