### ISSUE TITLE
structure / bounding box not working

### ISSUE THREAD

**Issue by fuzzwizzard** [maruohon/minihud#211]
Currently playing in 1.17.1 single player with Mini Hud installed, previously I had enabled the bounding and structure box for a nether fortress and that had worked, but now I am trying to use it again for an ocean monument and it won't render. 

All required toggles are set to true i.e. structure main toggle and ocean monument toggle, and the hex code is a value to be non transparent. I tested this by resetting the toggles, going to a fortress and toggling there, which worked fine, bounding box and structure were shown. I am just having trouble with the ocean monument.

**Comment by maruohon** [comment]
Are you looking at it from above or below the water surface? Depending on the rendering settings, it may just not render through the water surface, due to render order and depth test issues...

**Comment by fuzzwizzard** [comment]
It was really as simple as that, wow! Now I feel stupid. Thank you for the fast response 👍

**Comment by maruohon** [comment]
Obviously this is not ideal or intended, so I'll try to fix this at some point, if it's feasible. I'm still not an expert in rendering things, and these translucent rendering/render order related things are actually pretty complicated AFAIK.

**Comment by fuzzwizzard** [comment]
I did try and search for someone who had already experienced this before and couldn't find anything, so it doesn't seem to be a widespread issue people are running into. I just didn't consider that the water was stopping it from rendering, should've put 2 and 2 together when the ocean ruin next to the monument also didn't render in testing. Thank you though
