### ISSUE TITLE
No text shadow

### ISSUE THREAD

**Issue by RaptaG** [maruohon/minihud#212]
I think it's a good idea to add text shadow for a better visibility when someone has the text background to #00000000

**Comment by maruohon** [comment]
You mean like these options?
![image](https://user-images.githubusercontent.com/2331050/151986691-5f944fe9-dc7f-4293-99c7-c0912c09d1ca.png)

**Comment by RaptaG** [comment]
Yep, once again, I'm an idiot. Sorry..
