### ISSUE TITLE
game crash when loading beacon overlay

### ISSUE THREAD

**Issue by electricsteve** [maruohon/minihud#216]
when i go farm away from my home and i come back and place beacon and load overlay/load the beaconrangeoverlay the game crashes but when i load it when i come in the server it doesn't crash and when i place it in range of the place where i spawned it also doesn't crash.
it doesn't say it's from mini-hud in the launcher but when i install a mod wich can see the issue it say that the two things that let it crash are malilib and mini-hud.

**Comment by maruohon** [comment]
Post the crash log please so I don't have to stare at everything to try to figure out what the issue might be...

**Comment by electricsteve** [comment]
where can i find it?

**Comment by electricsteve** [comment]
[crash-2022-02-22_18.15.16-client.txt](https://github.com/maruohon/minihud/files/8122896/crash-2022-02-22_18.15.16-client.txt)
i think this is it
