### ISSUE TITLE
Village boundingbox does not render 

### ISSUE THREAD

**Issue by naecker21** [maruohon/minihud#228]
I tried to get the Village boundingbox shown, but it will never render. Any other boundingbox will render but the village not at all

**Comment by maruohon** [comment]
You didn't provide any information of what versions you are using... But if I'm taking a guess, you are probably in MC 1.18.2. The current MiniHUD version for 1.18.2 has many of the structure bounding box overlays broken. The structures changed a lot in vanilla in 1.18.2, and I didn't realize that until recently, so the overlay renderer was not updated properly to match the new structures in vanilla.

**Comment by maruohon** [comment]
The structure bounding boxes were fixed in the new 1.18.2 version (0.22.1), and it's also fixed in the "official" 1.19+ versions that were released a few days ago.
