### ISSUE TITLE
RealisticSeasons support?

### ISSUE THREAD

**Issue by Scarlaid** [maruohon/minihud#229]
While playing on a server, I realized they are using a plugin to add **seasons** 
The name goes by [RealisticSeasons](https://www.spigotmc.org/resources/realisticseasons-1-16-3-1-18-2-seasons-in-your-minecraft-world-with-temperature-and-calendar.93275/)
Any chance, if possible, adding Biome support for this plugin?

I am not sure if this *feature* even need, but worth the try, at least it wont show stuff like this:
![image](https://user-images.githubusercontent.com/90851437/161475734-546d2a5d-8187-407c-8d01-f8db37851210.png)

**Comment by maruohon** [comment]
If you mean just the biome name, then there is nothing I can do that would work automatically. MiniHUD tries to get the localized name of the biome, but if it's added by a server-side mod or plugin, then the client won't have the localization for that in any case.

And I'm not going to hard-code some list of biome names in other mods in MiniHUD, that's just extra maintenance overhead, and that list would probably get outdated pretty quickly unless someone keeps on top of the changes in those other mods and updates it periodically. And that's not me.
