### ISSUE TITLE
Opening Shape Editor crashes game.

### ISSUE THREAD

**Issue by Frustrated-Programmer** [maruohon/minihud#23]
When opening the config menu and clicking "Shapes" and/or setting and using a keybind to open the "Shape Editor" both crashes the game. My log:
[crash-2019-10-11_17.19.17-client.txt](https://github.com/maruohon/minihud/files/3719793/crash-2019-10-11_17.19.17-client.txt)

I got the MiniHud download from: https://www.curseforge.com/minecraft/mc-mods/mini-hud/files

Mods I have loaded:

    malilib-rift-1.13.2-0.10.0-dev.19
    minihud-rift-1.13.2-0.19.0-dev.20190609.195448
    OptiFine_1.13.2_HD_U_E7
    riftmod_voxelMap_1.8.2_for_1.13.2

Am using `RIFT 1.13.2` and MultiMC if that helps anything.
Let me know if you need anymore data / info.

**Comment by vacla** [comment]
you need version from 20190615, you accidently downloaded an older version, newest version: https://www.curseforge.com/minecraft/mc-mods/mini-hud/files/2725107

**Comment by maruohon** [comment]
I'm closing this, as the issue was an outdated mod version.
