### ISSUE TITLE
Is beacon distance renderer supported in 1.16.5?

### ISSUE THREAD

**Issue by Dan-k391** [maruohon/minihud#233]
Is the beacon distance renderer supported in 1.16.5?
I don't see an option that can enable this renderer, is it supported in this version?

![image](https://user-images.githubusercontent.com/73747609/164913472-368bc1ad-455f-4018-84e8-671e90864e55.png)

**Comment by maruohon** [comment]
No, it was originally added to the 1.12.2 version, and then somewhat recently I ported it to the 1.18.1 version I think?

It will come to the other versions once the 1.12.2 code is ready to be ported forward, but I have no idea how long that will still take.

**Comment by Dan-k391** [comment]
OK, thank you
