### ISSUE TITLE
port to 1.19

### ISSUE THREAD

**Issue by ghost** [maruohon/minihud#244]
malilib needs to be ported too...

**Comment by vacla** [comment]
@mharbb a quote from masa:
I know about 1.19 being out. I've been busy IRL and haven't had time to do any modding in a number of weeks. There is much to do for the 1.19 ports because I want to make them based on the newer development code from 1.12.2. So no ETAs.

**Comment by ghost** [comment]
> @mharbb a quote from masa: I know about 1.19 being out. I've been busy IRL and haven't had time to do any modding in a number of weeks. There is much to do for the 1.19 ports because I want to make them based on the newer development code from 1.12.2. So no ETAs.

k

**Comment by CrazyWolf13** [comment]
Why can't he just upload a temporary port without the newer code i need this mod lol

> @mharbb a quote from masa: I know about 1.19 being out. I've been busy IRL and haven't had time to do any modding in a number of weeks. There is much to do for the 1.19 ports because I want to make them based on the newer development code from 1.12.2. So no ETAs.

**Comment by kosma** [comment]
Unofficial community ports: https://kosma.pl/masamods/

**Comment by CrazyWolf13** [comment]
> Unofficial community ports: https://kosma.pl/masamods/

Why did no one told me about this earlier lol.
Thanks very much.

**Comment by CrazyWolf13** [comment]
> Unofficial community ports: https://kosma.pl/masamods/

Is there also a malilib version? cause its required but no there.

**Comment by kosma** [comment]
> Is there also a malilib version? cause its required but no there.

I suggest glasses, it is there :)

**Comment by CrazyWolf13** [comment]
> > Is there also a malilib version? cause its required but no there.
> 
> I suggest glasses, it is there :)

Damm, I must have been blind lol,  thanks.

**Comment by Wolkenfarmer** [comment]
I think this issue can be closed now xD

**Comment by mharbb** [comment]
Lmao yeah> I think this issue can be closed now xD

**Comment by ghost** [comment]
> I think this issue can be closed now xD

Yeah Lmao
