### ISSUE TITLE
Text Scale option does not save

### ISSUE THREAD

**Issue by LostLuma** [maruohon/minihud#245]
The `Info Lines HUD Settings -> Text Scale` option does not seem to persist between game restarts.

I'm currently running the latest version of minihud (`minihud-liteloader-1.12.2-0.41.0`), as well as these other mods:
- `itemscroller-liteloader-1.12.2-0.31.0`
- `litematica-liteloader-1.12.2-0.31.0`
- `malilib-liteloader-1.12.2-0.52.0`
- `OptiFine_1.12.2_HD_U_G5`
- `tweakeroo-liteloader-1.12.2-0.31.0`

**Comment by maruohon** [comment]
Yes this is a known issue in the current versions. The Info Overlay system still needs some changes to properly track config changes and save the settings. And it also still needs some other changes and improvements as well. Basically that system still isn't finished, and also MiniHUD's info line stuff (and how it hooks to the Info Overlay system) will also still get an almost total rewrite.

**Comment by LostLuma** [comment]
This seems to be resolved in the latest versions.
