### ISSUE TITLE
Menu won't open

### ISSUE THREAD

**Issue by TheCuteIDKKitty** [maruohon/minihud#247]
version: 1.12.2 forge
so, my menu won't open using H + C. I saw another thing saying go to your config and search for openConfigGui or something like that and it's literally not in minihud.cfg so i have absolutely no idea. kinda need this mod but it won't work. H also toggles the box in the top left so I know that the mod is working. Someone please help:) ty!!

**Comment by maruohon** [comment]
I assume you are then using the very old mod version 0.13.1 (from CurseForge)? That versions doesn't really even *have* any other features than the info lines thing, and it also doesn't have many of the later added info line types.

Assuming you want to use some of the overlays like Light Level Overlay, Slime Chunks, Structure Bounding Boxes etc. then you need the newer mod versions that also require the malilib library mod, as all of the config and keybind code etc. is in malilib nowadays. Those versions are currently not on CurseForge for 1.12.2, but instead here: https://masa.dy.fi/mcmods/client_mods/ I'll upload them to CurseForge again once the mod rewrites progress to a more finished state.

**Comment by TheCuteIDKKitty** [comment]
oml- thank you so much man. this is gonna save so much time with the shape renderer:))

**Comment by maruohon** [comment]
I don't remember if the Forge version there even has shapes yet... or maybe it only has the Despawn Sphere? It's quite old, from December 2019. I'll make new 1.12.2 Forge ports soon-ish fro the LiteLoader version, but there is at least one notable bug fix I need to do before that.
