### ISSUE TITLE
Bounding box doesn't work for 1.19.2

### ISSUE THREAD

**Issue by 5Grn** [maruohon/minihud#260]
I went to the nether to test the bounding box on a fortress, I turned on mainrenderingtoggle, then overlaystructuremaintoggle, the nether fortress but nothing happened. anyone got a fix for this
![2022-08-15_12 32 49](https://user-images.githubusercontent.com/96637203/184676337-f8373ef8-bacd-4ead-9df6-5d3308b2bf08.png)
?

**Comment by maruohon** [comment]
If you are on a server, then the server would need to have the Servux mod to send the structure data when MiniHUD requests for it. If you are in single player, then try toggling the structure main toggle option after you have the nether fortress type already enabled. Or if you use shaders then those might break the rendering, although I *think* it's supposed to work in the later MC versions with the most recent Iris versions. (although it will probably look weird.)

**Comment by 5Grn** [comment]
RIGHTTTTTTTTTTT I saw that on yt and completely forgot that Im on a hypixel smp XD thx m8

I also need malilib right?

**Comment by 5Grn** [comment]
oh wait, it still doesn't work...

![image](https://user-images.githubusercontent.com/96637203/184678766-d79e5d6e-f120-47a6-938c-80ff27b00c58.png)

**Comment by maruohon** [comment]
If you are on some Hypixel SMP that runs some kind of Bukkit variant, then it's just never going to work because the server doesn't have Servux installed.

**Comment by 5Grn** [comment]
aww... is there some kind of alternative to thi mod that works on a hypixel smp? Its hard to make a with skeleton farm without it

**Comment by maruohon** [comment]
Any alternative would then just have to guess the structure bounding box based on the blocks in the world. At that point you can just do that by hand as well. You could use the Box shape or Litematica's area selection boxes to just make a visual box for yourself based on the structure in the world.

**Comment by 5Grn** [comment]
ok thx
