### ISSUE TITLE
RealSpawnChunks not working in the 1.19.0 verison of the mod.

### ISSUE THREAD

**Issue by SuperSerferNow** [maruohon/minihud#267]
Whats in the video is incorrect? 
https://youtube.com/clip/Ugkx2E5yJ-wELgTMtV3rzWb3u_CMyXdsTeN8

**Comment by SuperSerferNow** [comment]
By incorrect I mean It didn't work btw

**Comment by SuperSerferNow** [comment]
No but I have the iris mod enabled but i'm not using it, it's broken for me but i'mma disable the mod

**Comment by SuperSerferNow** [comment]
I didn't even have the mod enabled in the first place

**Comment by SuperSerferNow** [comment]
It's broken bruh

**Comment by vacla** [comment]
You haven't really given much info to help you with.

**Comment by kosma** [comment]
Please go to the Discord for assistance. https://masa.dy.fi/discord

**Comment by SuperSerferNow** [comment]
ok ty
