### ISSUE TITLE
No keybind to toggle slime chunk overlay

### ISSUE THREAD

**Issue by ghost** [maruohon/minihud#273]
I've looked for a solid half hour and can't find the keybind. I checked the mod options config, and the in game keybind setter and can't find it anywhere.

**Comment by ghost** [comment]
I checked the config file and it said "PERIOD" was the keybind. So i've now tried that but it doesn't work

**Comment by aditeya24** [comment]
The config name is overlaySlimeChunks in the Renderers tab. If PERIOD doesn't work, try using something else like H+S for example. Also make sure the main rendering is enabled.

**Comment by Coathar** [comment]
The slime chunk overlay is under the "Renderers" tab. You have to set the keybind yourself by clicking the button next to the true/false button. 
![image](https://user-images.githubusercontent.com/16760243/190658294-e01df001-2d9e-4973-93de-3a43fa9c5a21.png)

You also need to make sure the mainRenderingToggle is on to see any of the renderers in MiniHUD.

**Comment by ghost** [comment]
Ok, thanks. :)
