### ISSUE TITLE
Game crashing after adding malilib

### ISSUE THREAD

**Issue by ExtremeLimit** [maruohon/minihud#28]
im trying to install minihud but it wasnt loading up so i searched on website that it needs malilib and i added it and now its crashing but if i dont get it then fabric says that minihud needs malilib

**Comment by maruohon** [comment]
Did you get the correct, latest version? Get the latest version of both for the MC version you play on from here: https://masa.dy.fi/tmp/minecraft/mods/client_mods/

**Comment by ExtremeLimit** [comment]
> Did you get the correct, latest version? Get the latest version of both for the MC version you play on from here: https://masa.dy.fi/tmp/minecraft/mods/client_mods/

ok i downloaded that one you linken and now:
The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

**Comment by vacla** [comment]
could you give the crashlog in a [pastebin](https://pastebin.com) ? @ExtremeLimit

**Comment by ExtremeLimit** [comment]
> could you give the crashlog in a [pastebin](https://pastebin.com) ? @ExtremeLimit

https://pastebin.com/CNKaE45T

here ya go

**Comment by vacla** [comment]
It seems you are using an older version of minihud

**Comment by ExtremeLimit** [comment]
ok now it works thank you very much
