### ISSUE TITLE
Renderer hotkeys tab and Sodium/Iris

### ISSUE THREAD

**Issue by nick-bors** [maruohon/minihud#291]
![image](https://user-images.githubusercontent.com/67550680/213267273-b6824417-65c7-4c7e-9821-2e15120b4529.png)
no renderer hotkeys tab. Using sodium and iris. Iris has the keybind <kbd>o</kbd> for light levels which conflicts w/ the minihud keybind for light levels. I unbound it but pressing <kbd>o</kbd> still doesn't work. I also happen to have mixin conflict helper as well as mixin stack trace and they log nothing so i don't know how to solve the issue. Is there a compatibility mod im missing?

**Comment by maruohon** [comment]
Did you look in the `Renderers` category...?

And `o` is not a default hotkey for anything in MiniHUD.
