### ISSUE TITLE
Maven repo not maintained

### ISSUE THREAD

**Issue by nick-bors** [maruohon/minihud#294]
The latest version of minihud on [your maven repo](https://masa.dy.fi/maven/fi/dy/masa/minihud/) is 1.16.4. Could you please add the fabric 1.19.x version to your repository? I am making a mod that will extend minihud's customizability

**Comment by maruohon** [comment]
Which 1.19.x version exactly? I haven't usually pushed the other mods than malilib to my maven at all except on special request a couple of times. I think most people have just been using the CurseMaven to pull them from CurseForge. This might change after the mod versions based on the rewrites come out though, as those are actually designed to be better/easier extendable.

I'm curious what aspects of MiniHUD will you be extending/changing? The entire info line system will be completely rewritten in the base mod during the mod rewrites to be fully customizable, using string placeholders.

**Comment by nick-bors** [comment]
> Which 1.19.x version exactly? I haven't usually pushed the other mods than malilib to my maven at all except on special request a couple of times. I think most people have just been using the CurseMaven to pull them from CurseForge. This might change after the mod versions based on the rewrites come out though, as those are actually designed to be better/easier extendable.
> 
> I'm curious what aspects of MiniHUD will you be extending/changing? The entire info line system will be completely rewritten in the base mod during the mod rewrites to be fully customizable, using string placeholders.

I would use curse maven yet its not properly downloading 
Decomp:
![image](https://user-images.githubusercontent.com/67550680/215328117-f53ba308-85c0-4fc4-9c0f-8ed83e0f1ab9.png)
Source from gh:
![image](https://user-images.githubusercontent.com/67550680/215328159-4fc8a98d-3123-4898-b725-08d356622491.png)

field_22789 doesnt exist in the class or in malilib's IRenderer

**Comment by nick-bors** [comment]
> the base mod during the mod rewrites to be fully customizable, using string placeholders.

I was going to do just this and make a custom config language. Basically alot like [custom hud](https://www.curseforge.com/minecraft/mc-mods/customhud) but with a few new things such as a more complete conditional system with chained conditions (logical operators like && and || ect). I'd be happy to help in my free time with it if you want me to

**Comment by maruohon** [comment]
`field_22789` is `width` in the vanilla `Screen` class. If you are left with the intermediary names then I assume you have the Gradle dependency set wrong and it's not remapping the dependency to the Yarn names?
