### ISSUE TITLE
So, I accidentally locked myself out of the menu

### ISSUE THREAD

**Issue by ttdhr-00** [maruohon/minihud#32]
What should I do?

**Comment by vacla** [comment]
In the config/ directory there is an file named minihud.json where you can add the hotkeys manual again if you deleted accidentally the config hotkey H + C

**Comment by maruohon** [comment]
If you are in 1.14.4 or 1.15+, then you can also use the Mod Menu mod (https://www.curseforge.com/minecraft/mc-mods/modmenu) to get a mod list, and my mods have a settings icon there which will open the configuration menu for each mod.
