### ISSUE TITLE
color renderer shows only black and structure are completely transparent

### ISSUE THREAD

**Issue by mrpyrocat** [maruohon/minihud#321]
I have the main rendering the overlay structure and the structue model set to true but the rendering does not show up and the color renderer is black transparent

![Screenshot 2023-09-07 144109](https://github.com/maruohon/minihud/assets/112426215/ce3674e6-99be-4940-b6cd-4bab254f21ce)
![Screenshot 2023-09-07 144253](https://github.com/maruohon/minihud/assets/112426215/d92200a5-9c55-4ce1-aaf6-3fcb41aeeae0)

**Comment by maruohon** [comment]
Are you using Optifine or otherwise shaders? Any other mods that do some significant rendering related stuff?

**Comment by mrpyrocat** [comment]
Starlight, lithium sodium indium

**Comment by maruohon** [comment]
It looks (mostly) fine for me using Lithium, Sodium, Indium.

![2023-09-25_19 39 25](https://github.com/maruohon/minihud/assets/2331050/8482e7a2-7dde-4743-a353-53be1dea3183)

So you would have to find which mod or setting somewhere is causing the issue. I can't do anything if I can't even reproduce the issue.

**Comment by mrpyrocat** [comment]
Color Editor is working again, it was because of the Dark UI Resourcepack from Vanilla tweaks, It still does not show up in game tho

**Comment by mrpyrocat** [comment]
I tried it with all mods off( except miniHUD) and no Resourcepacks and it still would not render in the world. Could it be that it does not work on servers?

**Comment by maruohon** [comment]
Oh was your original main issue that structure bounding boxes don't work on a server? I thought this was about messed up color rendering stuff in the menus (and in the world?). Structure bounding boxes in multiplayer require the server to have the Servux mod installed to send the structure data to MiniHUD when it requests for it. Without Servux on the server, you won't see any structures when playing on that server.

**Comment by mrpyrocat** [comment]
Both things were a problem. Thank you for your help.
