### ISSUE TITLE
Lightlevel overlay renders below snow layers

### ISSUE THREAD

**Issue by Vosjedev** [maruohon/minihud#337]
The light level overlay seems to render below snow layers on nearby blocks, making it unusable in snowy environments. It does however render the numbers on blocks further away...

![image](https://github.com/maruohon/minihud/assets/100359465/10268c45-32a1-4de8-a7a6-609c18fb45ea)

**Comment by maruohon** [comment]
There are several options in the Generic category for controlling the light level overlay behavior (search for `light`). I believe what you want in this case is `lightLevelAutoHeight`. The default options are set for fastest/least checks i.e. best performance when the overlay updates.

**Comment by Vosjedev** [comment]
Ah, thank you! That's the option I was searching for.
