### ISSUE TITLE
Trun on Overlay Spawn Chunk Real may lead to crash

### ISSUE THREAD

**Issue by MarcoGao123** [maruohon/minihud#338]
My game version is 1.20.1 and the minihud version is 0.27. When I played on a carpet server that ran on my computer, if I turned on the overlay spawn chunk real, the game would crash. But when I restart my game and try it again, It won't crash again.

**Comment by maruohon** [comment]
Can you send the crash log?

**Comment by MarcoGao123** [comment]
Sorry that I didn't upload it. I forget to save it for the first time, I switch a client and redo the action. Here is the error report.
[error report.zip](https://github.com/maruohon/minihud/files/14394383/error.report.zip)

**Comment by MarcoGao123** [comment]
There are three files in Chinese. The file starting with PCL is the log of the launcher, and the file with an extension of .bat is the startup script. The TXT file with all Chinese is the output before the game crash.

**Comment by maruohon** [comment]
I have sen this same crash reported a few times over time, but I still don't know what exactly causes it. Somehow some of the renderer stuff in MiniHUD has not been initialized correctly. The only reason I can think of is that somehow you are out of (video?) memory.

**Comment by MarcoGao123** [comment]
OK, Thank you for your reply. I hope you have a nice day.
