### ISSUE TITLE
[Suggestion] Tree Sapling Space Renderer

### ISSUE THREAD

**Issue by jodieblend** [maruohon/minihud#342]
It would be really cool if there was a renderer which would show you the needed space to grow. This could be useful for modded trees or just figuring out why your jungle tree won't grow.

**Comment by maruohon** [comment]
There isn't any way to get this information out of the game directly. It would need a ton of simulation runs to see what works and what doesn't. I don't usually like to add those type of features in these mods, as they are pretty complicated to implement, they are very performance heavy, and likely would often need updates during MC updates.
