### ISSUE TITLE
[Bug]Unable to break blocks at rest (without moving)

### ISSUE THREAD

**Issue by ImAurs** [maruohon/minihud#345]
Unable to break blocks at rest

**Comment by maruohon** [comment]
Did you somehow narrow this down to MiniHUD? There shouldn't be anything in MiniHUD capable of causing that kind of issue.

**Comment by AuroraRealm** [comment]
No

**Comment by maruohon** [comment]
:thinking: Then why did you post this issue here?

**Comment by AuroraRealm** [comment]
Because Unable to break blocks at rest....

**Comment by AuroraRealm** [comment]
I tried reconfiguring the config file, but it didn't work

**Comment by AuroraRealm** [comment]
Can't break blocks at rest when I enable minihud
Disable minihud and destroy blocks at rest

**Comment by maruohon** [comment]
What MC version and mod version are you using even? Does this happen also if you have only malilib and MiniHUD installed? (test in a separate single player test world if you have mods that you can't safely remove without breaking the world)
