### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by JackieJK** [maruohon/minihud#351]

**Comment by Samalando** [comment]
Masa has stated that he will not continue to update past 1.20.5 due to minor versions getting mod-breaking changes and he also has burnout. You can get 1.21 from [sakura ryokos github](https://github.com/sakura-ryoko), and that will be where the mods will get updated until further notice.

**Comment by JackieJK** [comment]
> Masa has stated that he will not continue to update past 1.20.5 due to minor versions getting mod-breaking changes and he also has burnout. You can get 1.21 from [sakura ryokos github](https://github.com/sakura-ryoko), and that will be where the mods will get updated until further notice.

cool
