### ISSUE TITLE
Support for 1.21.3?

### ISSUE THREAD

**Issue by Chromeyyy** [maruohon/minihud#367]
As the title says, can you please provide support for 1.21.3? Thanks in advance :)

**Comment by sakura-ryoko** [comment]
https://github.com/sakura-ryoko/minihud -- along with the other mods (MaLiLib / Litematica, etc) in my repos.

**Comment by Chromeyyy** [comment]
Oh. so you forked them and updated yourself?
Edit: Never mind, saw you were a maintainer on Modrinth. So these are like preview builds?

**Comment by sakura-ryoko** [comment]
Yep

**Comment by Chromeyyy** [comment]
Awesome. Quick question, the weather toggle shows that it's raining even though it clear. Is that a problem on my end?

**Comment by Chromeyyy** [comment]
![image](https://github.com/user-attachments/assets/fb854baa-117c-436a-92a9-ae9d9ce8bc0f)

**Comment by sakura-ryoko** [comment]
it's something on my "to check" list.
