### ISSUE TITLE
Suggest language file stripping

### ISSUE THREAD

**Issue by PeakXing** [maruohon/minihud#37]
Thanks to the author, this mod is very helpful to players!
But the language files have not been stripped, which has great resistance to translation. It is hoped that the language files will be separated to facilitate localization for enthusiasts of various countries.

Finally, thanks again to the author for making such a good mod!

**Comment by maruohon** [comment]
I'm not sure what you mean by that exactly? Do you mean things that are currently in the malilib lang file? Or the fact that the config option tooltips are not in the lang file?

I intend to move the config option tooltips/descriptions to the lang files in each mod before the next round of feature releases.

**Comment by PeakXing** [comment]
> I'm not sure what you mean by that exactly? Do you mean things that are currently in the malilib lang file? Or the fact that the config option tooltips are not in the lang file?
> 
> I intend to move the config option tooltips/descriptions to the lang files in each mod before the next round of feature releases.

yes i like it
