### ISSUE TITLE
"Renderer Toggles" Menu

### ISSUE THREAD

**Issue by nmichlo** [maruohon/minihud#39]
Currently, there does not seem to be a way to enable renderers without first assigning a hotkey.

Similar to the "Info Toggles" tab in the menu, it would be useful to have a "Renderer Toggles" tab as well, to complement the existing "Renderer Hotkeys" tab.

**Comment by nmichlo** [comment]
Edit: I am not familiar with modding, but it seems to have been surprisingly easy to add the feature after copying the code for "Info Toggles".

It is working based on very limited testing.

See pull request https://github.com/maruohon/minihud/pull/40 for 1.15.2

**Comment by maruohon** [comment]
Yes it's easy to add, the main problem currently is that there are already way too many config categories and on some GUI scales the buttons go outside the screen, or need to wrap to two or more lines (depending on the mod version and whether or not that category button wrapping is implemented), and the area for the config options gets even smaller.

There are lots of config GUI refactors planned for malilib, which are meant to allow for example easily defining custom config types, such as having the renderer toggle option and the hotkey in the same option/on the same line, and similarly for the info toggles the three separate tabs/categories will get merged to one category, as well as some other related improvements.

**Comment by nmichlo** [comment]
That makes sense, thank you for the response!

I look forward to those planned refactors!
