### ISSUE TITLE
overlaySpawnChunkReal is incorrect in 1.15.2

### ISSUE THREAD

**Issue by vichvich4444** [maruohon/minihud#41]
In 1.15.2 spawn chunks were changed. Seems like minihud renders outdated spawn chunks.
Also applies to overlaySpawnChunkPlayer.

**Comment by vacla** [comment]
OverlaySpawnchunksreal should be correct if you are on the latest version, if you see like 3 different borders or so, that has vanilla too.

**Comment by vichvich4444** [comment]
Picture. Mod renders 2 lazy chunk layers but there only one.
![2020-04-04_](https://user-images.githubusercontent.com/26071899/78424041-1a1e6800-766b-11ea-91b2-d783808131e5.jpg)

**Comment by maruohon** [comment]
Green are `ENTITY_TICKING`, then there is one shell of `TICKING` chunks, which process Block Entities but not Entities, and then there is one shell of `BORDER` chunks, which don't process anything, but mobs still count towards the mob cap.

Outside the red border up until the brown border are chunks that simply remain in memory after being loaded by something, but they don't process anything and don't count towards anything (they are no part of the world).

Edit: There is some more information about 1.14+ chunk loading here: https://gist.github.com/Drovolon/24bfaae00d57e7a8ca64b792e14fa7c6

**Comment by vichvich4444** [comment]
So there is no shell for BORDER type of spawn chunk. I was confused because of this (and don't think it's very handy)

**Comment by maruohon** [comment]
This overlay was first added in 1.12, when there were no chunk loading tickets and loading levels yet. Back then there was simply either unloaded chunks or loaded chunks, and if a chunk was surrounded with loaded chunks for at least 32 blocks on all sides (so basically the middle chunk of a 5x5 loaded area) then entities in it would get ticked. This concept became known as "lazy chunks" for those outer most 2 chunks beyond chunks that tick entities (although there was nothing at all different about the chunk itself.)

So the point of showing the spawn chunks in this way is that you can see the area where entities will get ticked, and then the "lazy chunks" where entities will not get ticked, but they would still count towards the mob cap. This was/is useful for building mob switches in spawn chunks (you would build the switch across the red boundary). The overlay was never really widely used for Block Entity or redstone processing, and back in 1.13.2 or before that would have still been anywhere inside the red border anyway.

So now in 1.14+ if you need it for Block Entity or redstone processing, you can either use the green area which processes them as well as regular entities, or if you need to know the exact outermost area for that then you can know that block entities and redstone still also work one chunk out from the green border. I guess I could add a separate border for those, but personally I think it's just adding more clutter.
