### ISSUE TITLE
Structure bounding boxes not working on Servux

### ISSUE THREAD

**Issue by Mythbusters123** [maruohon/minihud#47]
I have everything that is needed for structured so run enabled. I am running Servux and from the console, nothing is interfering. I just redownloaded mini hud and everything

**Comment by vacla** [comment]
@Mythbusters123 which MC version are you running?

**Comment by Mythbusters123** [comment]
1.15.2

**Comment by vacla** [comment]
@Mythbusters123 which mods on the server do you use?

**Comment by maruohon** [comment]
Is this still unsolved? This should be working if you are using a recent enough version of MiniHUD.
