### ISSUE TITLE
[Feature Request] Add C Counter Value

### ISSUE THREAD

**Issue by scottosx** [maruohon/minihud#5]
The C value on the F3 screen is very useful as a tactic to find open air spaces aka caves. It would be great to have it onscreen always with MiniHUD. Can't figure out if this is already implemented? TIA

**Comment by maruohon** [comment]
It's not currently available. I'll add this to my TODO list, I'll probably add it within the next few days.

**Comment by scottosx** [comment]
Very nice update. Thank you. The only thing that would be nice is you literally only need the C value, not D, L, pC, pU, aB.... that said I don't know what exactly is returned from the function for the Chunk Sections and if filtering is a problem (regex'd or whatever). 

Not a deal breaker as is but screen real estate and at-a-glance info is important. I am used to ignoring the rest of the info from F3 though so no biggie.

The effort in the update is much appreciated.

**Comment by maruohon** [comment]
Yeah, it was just that the method in vanilla where the C value to the F3 screen comes from, returns all of that stuff as a String. And the method or field where the C value itself comes from, was private, so I did it the easy way and used the entire String. I guess I could either use regex for that returned String, or reflection or a method handle to get the C value itself.

**Comment by maruohon** [comment]
I changed this in 0.11.1, and there is now a separate option to get the entire line, if someone would want that.
