### ISSUE TITLE
Inventory:The blocks are highlighted, Whilst the items and fences,ect. are dark grey, and haredly noticable

### ISSUE THREAD

**Issue by D0V1S** [maruohon/minihud#51]

**Comment by vacla** [comment]
Can you add a screenshot, versions of minihud and malilib, a list of mods you are using, to make it more clear what you mean?

**Comment by D0V1S** [comment]
> Can you add a screenshot, versions of minihud and malilib, a list of mods you are using, to make it more clear what you mean?

I use minihud,Malilib and optifine.
![2020-05-04_19 54 56](https://user-images.githubusercontent.com/64802092/80997135-30be0780-8e41-11ea-8838-1fcad1bde612.png)
 as you can see, some items are alot darker than the blocks.

**Comment by vacla** [comment]
did you try without minihud and malilib?

**Comment by D0V1S** [comment]
> did you try without minihud and malilib?

yup, its fixed when its without the mods...

**Comment by vacla** [comment]
which versions of malilib, minihud and minecraft?

**Comment by D0V1S** [comment]
> which versions of malilib, minihud and minecraft?

1.15.2

**Comment by vacla** [comment]
without minihud it looks good too, just malilib?

**Comment by D0V1S** [comment]
> without minihud it looks good too, just malilib?

i think its minihud, since malilib doesnt change in game stuff

**Comment by maruohon** [comment]
Does it get fixed if you just disable the HUD with `H`?

**Comment by D0V1S** [comment]
what i never closed it

**Comment by D0V1S** [comment]
uuuhm

**Comment by D0V1S** [comment]
lemme check

**Comment by D0V1S** [comment]
it does not.
its still glitched

**Comment by vacla** [comment]
what are the filenames of malilib and minihud?

**Comment by D0V1S** [comment]
minihud-forge-1.15.2-0.19.0-dev.20200412.215359.jar
malilib-forge-1.15.2-0.10.0-dev.20+beta.1.jar

**Comment by vacla** [comment]
how does it look without optifine but then with malilib and minihud?

**Comment by D0V1S** [comment]
> how does it look without optifine but then with malilib and minihud?

omg, its fixed, i guess its that version of optifine that doesnt work with forge,, tnx for ur help guys

**Comment by maruohon** [comment]
Yep looks like it's broken with just Optifine and Forge together without any other mods:
![2020-05-04_21 53 51](https://user-images.githubusercontent.com/2331050/81002366-c5c8fc80-8e51-11ea-9878-f4af674c18df.png)

However Optifine and my mods work fine together on Fabric:
![2020-05-04_21 51 56](https://user-images.githubusercontent.com/2331050/81002388-ce213780-8e51-11ea-95ff-9824df79ea42.png)
