### ISSUE TITLE
Display light levels underwater

### ISSUE THREAD

**Issue by InfoTeddy** [maruohon/minihud#53]
Since drowned spawn underwater 6 blocks below sea level, it'd be great to have the light level indicator also display light levels of blocks underwater, so people can light them up and be confident they've covered all drowned spawning spots appropriately.

**Comment by maruohon** [comment]
I think this was changed/implemented a while back in the main development version in 1.12.2. It should also be in the 1.16 snapshot versions, which have temporarily ported newer code from 1.12.2. You can use the 20w09a version of MiniHUD also on 1.15.2 (if that's the version you are playing on). It can be found here: https://masa.dy.fi/mcmods/client_mods/?mcver=1.16-snapshot-20w09a (Keep the other mods in their 1.15.2 versions, just get MiniHUD for 20w09a.)

**Comment by InfoTeddy** [comment]
Yes, I'm playing on 1.15.2. I'll take a look and try the 20w09a version of MiniHUD.

**Comment by InfoTeddy** [comment]
Ok, so I just installed the 20w09a version of MiniHUD. It doesn't look like the light level overlay shows up underwater? Do I have to enable an option or something?

**Comment by maruohon** [comment]
Hmm okay, maybe I remember it wrong then, or maybe I didn't port that part of the code correctly, since the same code had already been modified heavily in the 1.13+ versions or something. I'll need to take a look at it tomorrow maybe.

**Comment by maruohon** [comment]
Okay it definitely does exist in the 1.12.2 LiteLoader branch, so I assume I just accidentally omitted that change in the temporary port from 1.12.2 to 1.16 due to the other merge conflicts in that same part of code.

**Comment by InfoTeddy** [comment]
Also, unless I'm mistaken, it looks like installing the 20w09a version of MiniHUD mismatches item textures? Like my debug stick now has the texture of the "13" music disc, and then I downgrade to the 1.15.2 version of MiniHUD, and then it no longer has a mismatched texture.

**Comment by InfoTeddy** [comment]
Ok so this is in the latest version of MiniHUD (you have to be underwater for it to render, though), so I'm closing this issue.
