### ISSUE TITLE
Is there a way to increase the size of the info thing and move it to the right?

### ISSUE THREAD

**Issue by AppleGUY2812** [maruohon/minihud#54]
It is too small

**Comment by maruohon** [comment]
Yes, there is a `fontScale` option in the Generic config category of the config menu (`H + C`), and also a `hudAlignment` option to select which screen corner the lines should be at.

Also for simple support requests or questions like this, I would appreciate it if you used Discord instead, there is a `#masas-mods` channel on the SciCraft Discord: https://discord.gg/scicraft

**Comment by AppleGUY2812** [comment]
ok sorry
