### ISSUE TITLE
Overlays not rendering at all with Optifine

### ISSUE THREAD

**Issue by siasl** [maruohon/minihud#56]
I am unable to get any of the overlays like structers, slime chunks or light level to display while optifine is installed. I'm running on 1.15.2 and optifine 1.15.2 pre16. Using forge loader. The info HUD still shows on the top left, the overlays just don't render. When I uninstall optifine they do.

**Comment by maruohon** [comment]
I can't reproduce that...
![2020-05-15_22 18 23](https://user-images.githubusercontent.com/2331050/82088223-0817f680-96fa-11ea-9d16-9455f27c58d9.png)

**Comment by siasl** [comment]
Updating forge from 31.1.0 to 31.2.0 fixed it

**Comment by JJSax** [comment]
> Updating forge from 31.1.0 to 31.2.0 fixed it

I was running into the same issue.  I updated to that version of forge and now minihud h and h+c don't do anything.  Before it would say that they were toggled or bring up the menu.

edit: seems like suddenly none of my mods are working after updating forge.

**Comment by maruohon** [comment]
It works fine (or well, the same as before...) for me on 31.2.0.
