### ISSUE TITLE
Shapes color transparancy issue

### ISSUE THREAD

**Issue by LoneWolfProductions** [maruohon/minihud#57]
When changing the color on a shape it loses its transparancy.

Even when just opening the color editor without changing anything.

Version 1.16 snapshot 20w21a

![2020-05-25_21 32 24](https://user-images.githubusercontent.com/30441722/82839178-cb54b800-9ece-11ea-90fd-f91bc07b0a27.png)

**Comment by vacla** [comment]
if you change the first 2 characters of the color, that will change the transparancy.

**Comment by maruohon** [comment]
This was an issue in the earlier ColorEditor GUI implementation in malilib. It was fixed a while back in the 1.12.x version (here: https://github.com/maruohon/malilib/commit/991bea7052049eb28623407e1bc435784631eeac), so the fix will come to the other versions when the next merge happens.

**Comment by LoneWolfProductions** [comment]
Ok got it so i need to keep that on "#60??????" then.

Tnx
