### ISSUE TITLE
Minihud problem with multiplayer

### ISSUE THREAD

**Issue by AdamAwadalla08** [maruohon/minihud#61]
infoSlimeChunk does not work multiplayer even when player is OP

**Comment by vacla** [comment]
Did you do `/op ` or type `minihud-seed <seed>` in chat?

**Comment by AdamAwadalla08** [comment]
yes I did, kept pressing the infoSlimeChunk hotkey and the overlaySlimeChunks hotkey, does not work in multiplayer, whether OP or not, only works in SP

**Comment by maruohon** [comment]
Did you get the hotbar message about the seed being set? If you are OP, did you also try `/seed`?

Also you gave no information at all about the version you are using. Which Minecraft version, mod loader version and mod version are you using?

**Comment by AdamAwadalla08** [comment]
@maruohon first question, yes and yes
and second question, Im using Fabric loader 1.16.1, and the latest version of your mod (pre-3)

**Comment by maruohon** [comment]
I now uploaded 1.16.0 versions of the mods, and that MiniHUD build has a fix for this bug.

**Comment by AdamAwadalla08** [comment]
Thanks, Ill download it and tell you if there's anything

**Comment by AdamAwadalla08** [comment]
It's working just fine @maruohon , thanks
