### ISSUE TITLE
[Feature] Biome Borders

### ISSUE THREAD

**Issue by supersaiyansubtlety** [maruohon/minihud#71]
It would be incredibly useful to be able to visualize biome borders. 
I just started making a river-biome drowned farm with a friend and looked for a Fabric-equivalent of Biome Border Viewer and found none. Seems like it would fit well into minihud.

**Comment by maruohon** [comment]
This feature is on the todo list for MiniHUD. But unfortunately my todo list is very long, and since main development still happens in 1.12.2, it will additionally take a long time for new features to arrive to the versions of the mod for the later MC versions...

**Comment by supersaiyansubtlety** [comment]
Ok, well good to hear it's on the list anyways.

**Comment by supersaiyansubtlety** [comment]
Looks like this was added in 0.21.2, thanks!
