### ISSUE TITLE
[Suggestion] Indication if Diamond Ore or Ancient Debris have been mined in current chunk

### ISSUE THREAD

**Issue by javiersalcedo** [maruohon/minihud#77]
Disclaimer: I'm not a developer so I dont know how this could be done, just a user and fan of your mods

Since Diamond Ore veins generate only once per chunk, and an Ancient Debris vein generate between Y=8 to 22 (with the second Ancient Debris vein generating much less in comparison), a text line in the HUD saying if those blocks have been mined by the player in the current chunk could be a nice help for resource gathering, like when doing strip mining with tunnels with a short distance from each other

**Comment by maruohon** [comment]
This seems like a feature that many would probably consider quite cheaty, at least it seems like it to me...

**Comment by javiersalcedo** [comment]
I agree it is a little cheaty! Some veins generating at chunk borders would make this tool not always reliable, but it would make for a different way of doing strip mining for sure. From my limited knowledge. I believe that players on servers wouldn't be able to know when other players previously mined the ores as well
