### ISSUE TITLE
Add Sodium Vram F3 value in the Menu

### ISSUE THREAD

**Issue by User198263321** [maruohon/minihud#85]
Can you add the VRAM option in the F3 menu from sodium? 
![image](https://user-images.githubusercontent.com/53535277/91075616-5b101c80-e60c-11ea-9116-c038b4e8aab2.png)

**Comment by maruohon** [comment]
This is Sodium-specific and would only work with Sodium present, and it would introduce a compile-time dependency on Sodium, so it's probably not going to happen.
