### ISSUE TITLE
[Question/Suggestion] Question about config menu & different info in different positions?

### ISSUE THREAD

**Issue by bellyrose** [maruohon/minihud#87]
1: What's the button next to the Info Line Order number do? [This here.](https://i.imgur.com/CRDfiKW.png)
2: Am I able to have different info lines in different locations? For example, I want FPS and ping in the top right and position info in the bottom right.

**Comment by maruohon** [comment]
1: it switches the config widget between a text field and a slider
2: Not in the current version, but there are changes planned that will allow you to define as many different info line areas as you want, and add any type of "info text providers" to those, not only from MiniHUD but also from the other mods. All the details of that system aren't know at this point yet.

**Comment by bellyrose** [comment]
Sounds cool, keep up the good work ^^
