### ISSUE TITLE
Shapes Not Working

### ISSUE THREAD

**Issue by tk30456** [maruohon/minihud#95]
I play on a server and I was using the despawn sphere fine, but all the sudden it stopped working. I have tried to re download minihud, but nothing changes. I have a render hotkey set, but I still dont know why it is not working. The sphere also does not work on a single player world.

**Comment by maruohon** [comment]
The shapes essentially have 3 options that need to be enabled for them to render:
* The main rendering toggle (`H`) that turns off ALL rendering in the mod
* The shape renderer needs to be enabled (with the hotkey from Renderer Hotkeys)
* The shape itself needs to be enabled

In addition to these, if you accidentally set a fully transparent color for the shape, then you won't see it even though it would technically be rendering still.

And also, Optifine shader packs might simply break all overlay rendering, such as the shapes.
